---

# Task #1 Ensure Ubuntu Runs Python 3

- name: Install Python 2
  become: yes
  command: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

- name: Install Python 3
  become: yes
  command: update-alternatives --install /usr/bin/python python /usr/bin/python3.6 2

- name: Set Python 3 as Default
  become: yes
  command: update-alternatives --set python /usr/bin/python3.6

# Task #2
- name: Upgrade Ansible
  become: yes
  command: pip3 install --upgrade ansible

# Task #3
- name: Upgrade OpenStackSDK
  become: yes
  command: pip3 install --upgrade openstacksdk

# Task #4
- name: Upgrade Python for Kafka
  become: yes
  command: pip3 install kafka-python

# Task #5
- name: Upgrade Python for OpenStack
  become: yes
  command: pip3 install python-openstackclient

# Task #6 Copy Producer and Consumer

- name: Copy Producer
  copy:
    src: producer.py
    dest: ~/

- name: Copy Consumer
  copy:
    src: producer.py
    dest: ~/

...

